### PR TITLE
Add support for pseudo class nth-child

### PR DESCRIPTION
**Pull request by davide**

### CODE REVIEW

**Comment by davide** [comment]
Hi there! Can you please accept this pull request and update the associated npm module?
I have to keep a number of forks to actually use this patch: ccauron <- html-select <- node-trumpet <- harmon. Thanks!

**Comment by kusmi** [comment]
Yes, would really be great if this gets added! I also need nth-child functionality

**Comment by chrisdickinson** [comment]
Thanks! Merged and published as v1.3.0!

**Comment by davide** [comment]
Awesome! Thank you!
Onwards to the next repository. :)

**Pull request merged**
